/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentmanagementsystem;

import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import studentmanagementsystem.Instructor;
import java.io.*;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author MAHMOUD TALAAT
 */
public class Admininterface extends javax.swing.JFrame {

    /**
     * Creates new form Admininterface
     */
    public Admininterface() {
        initComponents();
        this.setVisible(true);
        
    }
     /* This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        popupMenu1 = new java.awt.PopupMenu();
        jFileChooser1 = new javax.swing.JFileChooser();
        Studenttabpanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        InstIDip = new javax.swing.JTextField();
        InstNameip = new javax.swing.JTextField();
        INT = new javax.swing.JLabel();
        IIDT = new javax.swing.JLabel();
        AddInstButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        courseip = new javax.swing.JTextField();
        RemoveButton = new javax.swing.JButton();
        SearchInstButton = new javax.swing.JButton();
        SetCTIButton = new javax.swing.JButton();
        RemoveCourseButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        InstTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        text1 = new javax.swing.JLabel();
        text3 = new javax.swing.JLabel();
        SCourseip = new javax.swing.JTextField();
        Gradeip = new javax.swing.JTextField();
        AddstudButton = new javax.swing.JButton();
        RemoveStudButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        StudeNameip = new javax.swing.JTextField();
        StudIDip = new javax.swing.JTextField();
        EditStudNameButton = new javax.swing.JButton();
        SetGradeButton = new javax.swing.JButton();
        SetCourseButton = new javax.swing.JButton();
        RemoveStudCourseButton = new javax.swing.JButton();
        SearchStudentButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        StudentTable = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CourseNameip = new javax.swing.JTextField();
        AddCourseButton = new javax.swing.JButton();
        SearchCourseButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        CourseTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        SetInstructorip = new javax.swing.JTextField();
        SetInstructorButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Studenttabpanel.setBackground(new java.awt.Color(255, 255, 255));
        Studenttabpanel.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        Studenttabpanel.setPreferredSize(new java.awt.Dimension(1500, 696));

        jPanel1.setPreferredSize(new java.awt.Dimension(1500, 697));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InstIDip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstIDipActionPerformed(evt);
            }
        });
        jPanel7.add(InstIDip, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 227, -1));

        InstNameip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstNameipActionPerformed(evt);
            }
        });
        jPanel7.add(InstNameip, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 230, -1));

        INT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        INT.setText("Instructor Name :");
        jPanel7.add(INT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        IIDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IIDT.setText("Instructor ID :");
        jPanel7.add(IIDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        AddInstButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AddInstButton.setForeground(new java.awt.Color(51, 51, 51));
        AddInstButton.setText("Add Instructor");
        AddInstButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddInstButtonMouseClicked(evt);
            }
        });
        AddInstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddInstButtonActionPerformed(evt);
            }
        });
        jPanel7.add(AddInstButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 150, -1));

        EditButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EditButton.setText("Edit Name");
        EditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditButtonMouseClicked(evt);
            }
        });
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });
        jPanel7.add(EditButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 150, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Course :");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, -1, -1));

        courseip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseipActionPerformed(evt);
            }
        });
        jPanel7.add(courseip, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 190, -1));

        RemoveButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RemoveButton.setText("Remove Instructor");
        RemoveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveButtonMouseClicked(evt);
            }
        });
        jPanel7.add(RemoveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 150, -1));

        SearchInstButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SearchInstButton.setText("Search");
        SearchInstButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchInstButtonMouseClicked(evt);
            }
        });
        jPanel7.add(SearchInstButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 150, -1));

        SetCTIButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SetCTIButton.setText("Set Course");
        SetCTIButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SetCTIButtonMouseClicked(evt);
            }
        });
        jPanel7.add(SetCTIButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 150, -1));

        RemoveCourseButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RemoveCourseButton.setText("Remove Course");
        RemoveCourseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveCourseButtonMouseClicked(evt);
            }
        });
        jPanel7.add(RemoveCourseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 140, 150, -1));

        InstTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Instructor Name", "Courses"
            }
        ));
        InstTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InstTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(InstTable);
        if (InstTable.getColumnModel().getColumnCount() > 0) {
            InstTable.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 840, 280));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        Studenttabpanel.addTab("Instructors", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(416, 137));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text1.setText("Student Name :");
        jPanel3.add(text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 88, -1, -1));

        text3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text3.setText("Student ID :");
        jPanel3.add(text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 98, -1));

        SCourseip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SCourseipActionPerformed(evt);
            }
        });
        jPanel3.add(SCourseip, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 38, 213, -1));

        Gradeip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradeipActionPerformed(evt);
            }
        });
        jPanel3.add(Gradeip, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 88, 213, -1));

        AddstudButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AddstudButton.setForeground(new java.awt.Color(51, 51, 51));
        AddstudButton.setText("Add Student");
        AddstudButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddstudButtonMouseClicked(evt);
            }
        });
        AddstudButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddstudButtonActionPerformed(evt);
            }
        });
        jPanel3.add(AddstudButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 143, 146, -1));

        RemoveStudButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RemoveStudButton.setText("Remove Student");
        RemoveStudButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveStudButtonMouseClicked(evt);
            }
        });
        RemoveStudButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveStudButtonActionPerformed(evt);
            }
        });
        jPanel3.add(RemoveStudButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 143, 146, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Course :");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText(" Total Grade :");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 88, 90, -1));
        jPanel3.add(StudeNameip, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 88, 213, -1));

        StudIDip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudIDipActionPerformed(evt);
            }
        });
        jPanel3.add(StudIDip, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 38, 213, -1));

        EditStudNameButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EditStudNameButton.setText("Edit Name");
        EditStudNameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditStudNameButtonMouseClicked(evt);
            }
        });
        jPanel3.add(EditStudNameButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 143, 146, -1));

        SetGradeButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SetGradeButton.setText("Set Grade");
        SetGradeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SetGradeButtonMouseClicked(evt);
            }
        });
        SetGradeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetGradeButtonActionPerformed(evt);
            }
        });
        jPanel3.add(SetGradeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(873, 143, 146, -1));

        SetCourseButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SetCourseButton.setText("Set Course");
        SetCourseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SetCourseButtonMouseClicked(evt);
            }
        });
        jPanel3.add(SetCourseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 143, 146, -1));

        RemoveStudCourseButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RemoveStudCourseButton.setText("Remove Couse");
        RemoveStudCourseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveStudCourseButtonMouseClicked(evt);
            }
        });
        jPanel3.add(RemoveStudCourseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 143, 146, -1));

        SearchStudentButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SearchStudentButton.setText("Search");
        SearchStudentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchStudentButtonMouseClicked(evt);
            }
        });
        jPanel3.add(SearchStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 192, 146, -1));

        StudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Courses", "Total Grade"
            }
        ));
        StudentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(StudentTable);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 253, 794, 290));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1047, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                .addContainerGap())
        );

        Studenttabpanel.addTab("Students", jPanel2);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Course Name :");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 120, -1));

        CourseNameip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseNameipActionPerformed(evt);
            }
        });
        jPanel8.add(CourseNameip, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 180, -1));

        AddCourseButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AddCourseButton.setText("Add Course");
        AddCourseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddCourseButtonMouseClicked(evt);
            }
        });
        jPanel8.add(AddCourseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 140, -1));

        SearchCourseButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SearchCourseButton.setText("Search");
        SearchCourseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchCourseButtonMouseClicked(evt);
            }
        });
        jPanel8.add(SearchCourseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 140, -1));

        CourseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Nmae", "Instructor ID", "Instructor's Name "
            }
        ));
        CourseTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CourseTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(CourseTable);

        jPanel8.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 740, 610));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Instructor's ID :");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 160, -1));
        jPanel8.add(SetInstructorip, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 170, -1));

        SetInstructorButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SetInstructorButton.setText("Set Instructor ");
        SetInstructorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SetInstructorButtonMouseClicked(evt);
            }
        });
        jPanel8.add(SetInstructorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 140, -1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Studenttabpanel.addTab("Courses", jPanel6);

        ExitButton.setText("Exit");
        ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Studenttabpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1142, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ExitButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ExitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Studenttabpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseClicked
        // TODO add your handling code here:
        new AppStart();
        this.dispose();
    }//GEN-LAST:event_ExitButtonMouseClicked

    private void RemoveStudButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveStudButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoveStudButtonActionPerformed

    private void AddstudButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddstudButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddstudButtonActionPerformed

    private void GradeipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradeipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GradeipActionPerformed

    private void SCourseipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SCourseipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SCourseipActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditButtonActionPerformed

    private void AddInstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddInstButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddInstButtonActionPerformed

    
    
/**************************************Instructor*************************************/
    
    private void AddInstButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddInstButtonMouseClicked
        // TODO add your handling code here:
        String name = InstNameip.getText();
        Course c =new Course(courseip.getText());
        if (name.equals("")|| InstIDip.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Enter Instructor Name and Id");
        }
        else{
            int id = Integer.parseInt(InstIDip.getText());
            if (c.equals("")){
                instructorsystem.addInst(id,name);
                JOptionPane.showMessageDialog(null,"Instructor Added");
            }
            else {
                instructorsystem.addInstructor(id, name,Arrays.asList(c));
                JOptionPane.showMessageDialog(null,"Instructor Added");
                if(instructorsystem.isinSys(id)){
                    DefaultTableModel model = (DefaultTableModel) InstTable.getModel();
                    Object rowdata[]=new Object[3];
                    rowdata[0]=instructorsystem.viewInstID(id);
                    rowdata[1]= instructorsystem.viewInstName(id);
                    rowdata[2]=instructorsystem.ShowInstCourses(id);
                    model.addRow(rowdata);
                }
            }
        }
    }//GEN-LAST:event_AddInstButtonMouseClicked

    private void InstNameipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstNameipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InstNameipActionPerformed

    private void InstIDipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstIDipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InstIDipActionPerformed

    private void StudIDipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudIDipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudIDipActionPerformed

    private void SetGradeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetGradeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SetGradeButtonActionPerformed

    private void EditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditButtonMouseClicked
        // TODO add your handling code here:
        
        String name = InstNameip.getText();
        if (name.equals("")|| InstIDip.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Enter Instructor Name and Id");
        }
        else{
            int id = Integer.parseInt(InstIDip.getText());
            instructorsystem.editInstructorName(id,name);
            JOptionPane.showMessageDialog(null,"Instructor Name Edited");
            if(instructorsystem.isinSys(id)){
                DefaultTableModel model = (DefaultTableModel) InstTable.getModel();
                //model.removeRow(id);
                Object rowdata[]=new Object[3];
                rowdata[0]=instructorsystem.viewInstID(id);    
                rowdata[1]= instructorsystem.viewInstName(id);
                rowdata[2]=instructorsystem.ShowInstCourses(id);
                model.addRow(rowdata);
            }
        }
    }//GEN-LAST:event_EditButtonMouseClicked

    private void RemoveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveButtonMouseClicked
        // TODO add your handling code here:
        if (InstIDip.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Enter Instructor Id");
        }
        else{
            int id = Integer.parseInt(InstIDip.getText());
           // instructorsystem.removeInstructor(id);
            JOptionPane.showMessageDialog(null,"Instructor Name Removed");
            DefaultTableModel model = (DefaultTableModel) InstTable.getModel();
            //model.removeRow(id);
            instructorsystem.removeInstructor(id);
        }
    }//GEN-LAST:event_RemoveButtonMouseClicked

    private void SetCTIButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SetCTIButtonMouseClicked
        // TODO add your handling code here:
        Course c =new Course(courseip.getText());
        if (InstIDip.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Enter Instructor Id");
        }
        else{
            int id = Integer.parseInt(InstIDip.getText());
            if (c.equals("")){
                JOptionPane.showMessageDialog(null,"Enter the Course");
            }
            else {
                instructorsystem.addInstructorCourse(id,c);
                JOptionPane.showMessageDialog(null,"The Course Added to Instructor");
                   DefaultTableModel model = (DefaultTableModel) InstTable.getModel();
                   Object rowdata[]=new Object[3];
                   //model.removeRow(id);
                   rowdata[0]=instructorsystem.viewInstID(id);
                   rowdata[1]= instructorsystem.viewInstName(id);
                   rowdata[2]=instructorsystem.ShowInstCourses(id);
                   model.addRow(rowdata);
                
            }
        }
    }//GEN-LAST:event_SetCTIButtonMouseClicked

    private void RemoveCourseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveCourseButtonMouseClicked
        // TODO add your handling code here:
        Course c =new Course(courseip.getText());
        if (InstIDip.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Enter Instructor Id");
        }
        else{
            int id = Integer.parseInt(InstIDip.getText());
            if (c.equals("")){
                JOptionPane.showMessageDialog(null,"Enter the Course");
            }
            else {
                instructorsystem.deleteInstructorCourse(id,c);
                JOptionPane.showMessageDialog(null,"The Course Added to Instructor");
                if(instructorsystem.isinSys(id)){
                   DefaultTableModel model = (DefaultTableModel) InstTable.getModel();
                   //model.removeRow(id);
                   Object rowdata[]=new Object[3];
                   rowdata[0]=instructorsystem.viewInstID(id);
                   rowdata[1]= instructorsystem.viewInstName(id);
                   rowdata[2]=instructorsystem.ShowInstCourses(id);
                   model.addRow(rowdata);
                }
            }
        }                                
    }//GEN-LAST:event_RemoveCourseButtonMouseClicked

    private void SearchInstButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchInstButtonMouseClicked
        // TODO add your handling code here:
        if (InstIDip.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Enter Instructor Id");
        }
        else{
            int id = Integer.parseInt(InstIDip.getText());
            if(instructorsystem.isinSys(id)){
                DefaultTableModel model = (DefaultTableModel) InstTable.getModel();
                TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(model);
                InstTable.setRowSorter(obj);
                obj.setRowFilter(RowFilter.regexFilter(InstIDip.getText()));
           }
        }
    }//GEN-LAST:event_SearchInstButtonMouseClicked

/*****************************************************************************************/

    private void CourseNameipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseNameipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CourseNameipActionPerformed

/**************************************Student*******************************************/
    
    private void AddstudButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddstudButtonMouseClicked
        // TODO add your handling code here:
        String name = StudeNameip.getText();
        Course c =new Course(SCourseip.getText());
      //  float grade =Float.parseFloat(Gradeip.getText()); 
        if (name.equals("")|| StudIDip.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Enter Student Name and Id");
        }
        else{
            int id = Integer.parseInt(StudIDip.getText());
            if (c.equals("")){
                studentsystem.addStudent(id,name);
                JOptionPane.showMessageDialog(null,"Student Added");
            }
            else {
                studentsystem.addStudent(id, name,c);
                JOptionPane.showMessageDialog(null,"Student Added");
                if(studentsystem.isinSys(id)){
                    DefaultTableModel model = (DefaultTableModel) InstTable.getModel();
                    Object rowdata[]=new Object[4];
                    rowdata[0]=studentsystem.viewstudID(id);
                    rowdata[1]= studentsystem.viewstudName(id);
                    rowdata[2]=studentsystem.ShowStudCourses(id);
                    rowdata[3]=studentsystem.getStudgrades(id);
                    model.addRow(rowdata);
                }
            }
        }
        
        
        
    }//GEN-LAST:event_AddstudButtonMouseClicked

    private void EditStudNameButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditStudNameButtonMouseClicked
        // TODO add your handling code here:
        String name = StudeNameip.getText();
      //float grade =Float.parseFloat(Gradeip.getText()); 
        if (name.equals("")|| StudIDip.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Enter Student Name and Id");
        }
        else{
            int id = Integer.parseInt(StudIDip.getText());
            studentsystem.editStudent(id,name);
            JOptionPane.showMessageDialog(null,"Student Name Edited");
            if(studentsystem.isinSys(id)){
                    DefaultTableModel model = (DefaultTableModel) InstTable.getModel();
                    model.removeRow(id);
                    Object rowdata[]=new Object[4];
                    rowdata[0]=studentsystem.viewstudID(id);
                    rowdata[1]= studentsystem.viewstudName(id);
                    rowdata[2]=studentsystem.ShowStudCourses(id);
                    rowdata[3]=studentsystem.getStudgrades(id);
                    model.addRow(rowdata);
            }
        }
    }//GEN-LAST:event_EditStudNameButtonMouseClicked

    private void courseipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseipActionPerformed

    private void RemoveStudButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveStudButtonMouseClicked
        // TODO add your handling code here:
        if (InstIDip.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Enter Student Id");
        }
        else {
            int id = Integer.parseInt(StudIDip.getText());
            studentsystem.removeStudent(id);
            JOptionPane.showMessageDialog(null,"The Student Removed");
            DefaultTableModel model = (DefaultTableModel) StudentTable.getModel();
            model.removeRow(id);
        }
    }//GEN-LAST:event_RemoveStudButtonMouseClicked

    private void SetCourseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SetCourseButtonMouseClicked
        // TODO add your handling code here:
        Course c =new Course(SCourseip.getText());
        if (StudIDip.getText().equals("")||SCourseip.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Enter Student Id and Course");
        }
        else{
            double grade =Double.parseDouble(Gradeip.getText());
            Grade g = new Grade();
            g.setGradeValue(grade);
            int id = Integer.parseInt(StudIDip.getText());
            if (Gradeip.getText().equals("")){
                studentsystem.SetcourseStudent(id,c);
                JOptionPane.showMessageDialog(null,"he Course Added to Stedent");
            }
            else {
                studentsystem.setcoursetoStudent(id,c,g);
                JOptionPane.showMessageDialog(null,"The Course and Grade Added to Student");
                if(studentsystem.isinSys(id)){
                   DefaultTableModel model = (DefaultTableModel) StudentTable.getModel();
                   model.removeRow(id);
                   Object rowdata[]=new Object[4];
                   rowdata[0]=studentsystem.viewstudID(id);
                   rowdata[1]= studentsystem.viewstudName(id);
                   rowdata[2]=studentsystem.ShowStudCourses(id);
                   rowdata[3]=studentsystem.getStudgrades(id);
                   model.addRow(rowdata);
                }
            }
        }
    }//GEN-LAST:event_SetCourseButtonMouseClicked

    private void RemoveStudCourseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveStudCourseButtonMouseClicked
        // TODO add your handling code here:
        Course c =new Course(SCourseip.getText());
        if (StudIDip.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Enter Instructor Id");
        }
        else{
            int id = Integer.parseInt(StudIDip.getText());
            if (c.equals("")){
                JOptionPane.showMessageDialog(null,"Enter the Course");
            }
            else {
                studentsystem.removecourseStudent(id,c);
                JOptionPane.showMessageDialog(null,"The Course Added to Instructor");
                 if(studentsystem.isinSys(id)){
                   DefaultTableModel model = (DefaultTableModel) StudentTable.getModel();
                   model.removeRow(id);
                   Object rowdata[]=new Object[4];
                   rowdata[0]=studentsystem.viewstudID(id);
                   rowdata[1]= studentsystem.viewstudName(id);
                   rowdata[2]=studentsystem.ShowStudCourses(id);
                   rowdata[3]=studentsystem.getStudgrades(id);
                   model.addRow(rowdata);
                }
            }
        }                                
    }//GEN-LAST:event_RemoveStudCourseButtonMouseClicked

    private void SetGradeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SetGradeButtonMouseClicked
        // TODO add your handling code here:
        Course c =new Course(SCourseip.getText());
        if (StudIDip.getText().equals("") || c.equals("") || Gradeip.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Enter Student ID, Course and Grade ");
        }
        else{
            double grade =Double.parseDouble(Gradeip.getText());
            Grade g = new Grade();
            g.setGradeValue(grade);
            int id = Integer.parseInt(StudIDip.getText());
            studentsystem.setgradetoStudent(id,c,g);
            JOptionPane.showMessageDialog(null,"Student ID: "+id + "\n Grade Added");
                if(studentsystem.isinSys(id)){
                   DefaultTableModel model = (DefaultTableModel) StudentTable.getModel();
                   model.removeRow(id);
                   Object rowdata[]=new Object[4];
                   rowdata[0]=studentsystem.viewstudID(id);
                   rowdata[1]= studentsystem.viewstudName(id);
                   rowdata[2]=studentsystem.ShowStudCourses(id);
                   rowdata[3]=studentsystem.getStudgrades(id);
                   model.addRow(rowdata);
                }
        }
    }//GEN-LAST:event_SetGradeButtonMouseClicked

/***************************************************************************************/

    
    
/******************************************Courses*********************************************/  
    
    private void AddCourseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddCourseButtonMouseClicked
        // TODO add your handling code here:
        Course c =new Course(SCourseip.getText());
        if (SCourseip.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Enter the course name");
        }
        else{
            if(SetInstructorip.getText().equals("")){
                courses cs=new courses();
                cs.insertCourse(c);
                DefaultTableModel model = (DefaultTableModel) CourseTable.getModel();
                Object rowdata[]=new Object[3];
                rowdata[0]=cs.printCourses(c);
                model.addRow(rowdata);
                JOptionPane.showMessageDialog(null,"Course Added");
            }
            else{
                int id = Integer.parseInt(SetInstructorip.getText());
                courses cs=new courses();
                cs.insertCourse(c);
                instructorsystem.addInstructorCourse(id,c);
                JOptionPane.showMessageDialog(null,"");
                DefaultTableModel model = (DefaultTableModel) CourseTable.getModel();
                Object rowdata[]=new Object[3];
                if(instructorsystem.isinSys(id)){
                    rowdata[0]=cs.printCourses(c);
                    rowdata[1]=instructorsystem.viewInstID(id);
                    rowdata[2]=instructorsystem.viewInstName(id);
                    model.addRow(rowdata);
                }
            }
        }
        
    }//GEN-LAST:event_AddCourseButtonMouseClicked

    private void SetInstructorButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SetInstructorButtonMouseClicked
        // TODO add your handling code here:
        if (SCourseip.getText().equals("")|| SetInstructorip.getText().equals("") ){
            JOptionPane.showMessageDialog(null,"Enter the course name and Instructor ID ");
        }
        else{
            Course c =new Course(SCourseip.getText());
            courses cs=new courses();
            int ID =Integer.parseInt(SetInstructorip.getText());
            instructorsystem.addInstructorCourse(ID,c);
            DefaultTableModel model = (DefaultTableModel) CourseTable.getModel();
                Object rowdata[]=new Object[3];
                if(instructorsystem.isinSys(ID)){
                    model.removeRow(ID);
                    rowdata[0]=cs.printCourses(c);
                    rowdata[1]=instructorsystem.viewInstID(ID);
                    rowdata[2]=instructorsystem.viewInstName(ID);
                    model.addRow(rowdata);
                }
            
        }
    }//GEN-LAST:event_SetInstructorButtonMouseClicked

    private void SearchStudentButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchStudentButtonMouseClicked
        // TODO add your handling code here:
        if (StudIDip.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Enter Instructor Id");
        }
        else{
            int id = Integer.parseInt(StudIDip.getText());
            if(instructorsystem.isinSys(id)){
                DefaultTableModel model = (DefaultTableModel) StudentTable.getModel();
                TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(model);
                StudentTable.setRowSorter(obj);
                obj.setRowFilter(RowFilter.regexFilter(StudIDip.getText()));
           }
        }
        
    }//GEN-LAST:event_SearchStudentButtonMouseClicked

    private void SearchCourseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchCourseButtonMouseClicked
        // TODO add your handling code here:
        if (SCourseip.getText().equals("") && SetInstructorip.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Enter Course or Instructor Name");
        }
        else{
            DefaultTableModel model = (DefaultTableModel) CourseTable.getModel();
            TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(model);
            CourseTable.setRowSorter(obj);
            obj.setRowFilter(RowFilter.regexFilter(SCourseip.getText()));
            obj.setRowFilter(RowFilter.regexFilter(SetInstructorip.getText()));
        }
        
    }//GEN-LAST:event_SearchCourseButtonMouseClicked

    private void InstTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstTableMouseClicked
       DefaultTableModel model = (DefaultTableModel) InstTable.getModel();
        int selectedrow= InstTable.getSelectedRow();
        InstIDip.setText(model.getValueAt(selectedrow, 0).toString());
        InstNameip.setText(model.getValueAt(selectedrow, 1).toString());
        courseip.setText(model.getValueAt(selectedrow, 2).toString());
    }//GEN-LAST:event_InstTableMouseClicked

    private void StudentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) InstTable.getModel();
        int selectedrow= InstTable.getSelectedRow();
        StudIDip.setText(model.getValueAt(selectedrow, 0).toString());
        StudeNameip.setText(model.getValueAt(selectedrow, 1).toString());
        SCourseip.setText(model.getValueAt(selectedrow, 2).toString());
        Gradeip.setText(model.getValueAt(selectedrow, 3).toString());
    }//GEN-LAST:event_StudentTableMouseClicked

    private void CourseTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseTableMouseClicked
      DefaultTableModel model = (DefaultTableModel) InstTable.getModel();
        int selectedrow= InstTable.getSelectedRow();
        CourseNameip.setText(model.getValueAt(selectedrow, 0).toString());
        SetInstructorip.setText(model.getValueAt(selectedrow, 1).toString());
    }//GEN-LAST:event_CourseTableMouseClicked

/**********************************************************************************************/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admininterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admininterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admininterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admininterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admininterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCourseButton;
    private javax.swing.JButton AddInstButton;
    private javax.swing.JButton AddstudButton;
    private javax.swing.JTextField CourseNameip;
    private javax.swing.JTable CourseTable;
    private javax.swing.JButton EditButton;
    private javax.swing.JButton EditStudNameButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField Gradeip;
    private javax.swing.JLabel IIDT;
    private javax.swing.JLabel INT;
    private javax.swing.JTextField InstIDip;
    private javax.swing.JTextField InstNameip;
    private javax.swing.JTable InstTable;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JButton RemoveCourseButton;
    private javax.swing.JButton RemoveStudButton;
    private javax.swing.JButton RemoveStudCourseButton;
    private javax.swing.JTextField SCourseip;
    private javax.swing.JButton SearchCourseButton;
    private javax.swing.JButton SearchInstButton;
    private javax.swing.JButton SearchStudentButton;
    private javax.swing.JButton SetCTIButton;
    private javax.swing.JButton SetCourseButton;
    private javax.swing.JButton SetGradeButton;
    private javax.swing.JButton SetInstructorButton;
    private javax.swing.JTextField SetInstructorip;
    private javax.swing.JTextField StudIDip;
    private javax.swing.JTextField StudeNameip;
    private javax.swing.JTable StudentTable;
    private javax.swing.JTabbedPane Studenttabpanel;
    private javax.swing.JTextField courseip;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text3;
    // End of variables declaration//GEN-END:variables
}
